// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/20/2024, 1:16:54 AM
const configMerger = require("/home/nikita/Desktop/gitir/ir-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/nikita/Desktop/gitir/ir-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/plugins/**/*.{js,ts,mjs}","/home/nikita/Desktop/gitir/ir-project/composables/**/*.{js,ts,mjs}","/home/nikita/Desktop/gitir/ir-project/utils/**/*.{js,ts,mjs}","/home/nikita/Desktop/gitir/ir-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/nikita/Desktop/gitir/ir-project/app.config.{js,ts,mjs}"] } }));

module.exports = config
